project_identifier: cli-test5
api_key: 3259af9269cd059be42eeaf1a1e01620
base_path: ''
base_url: ''
preserve_hierarchy: 1
files:
  - source: gettext-runtime.pot
    translation: '%two_letters_code%.po'
